! -*- fortran -*-
! $HEADER$
!
! *** THIS FILE IS AUTOMATICALLY GENERATED!
! *** Any manual edits will be lost!
!
      integer OMPI_HAVE_MPI_EXT
      parameter (OMPI_HAVE_MPI_EXT=1)
!
!
!     Enabled Extension: XCLFrame
!     No mpif.h bindings available
!
      integer OMPI_HAVE_MPI_EXT_XCLFRAME
      parameter (OMPI_HAVE_MPI_EXT_XCLFRAME=0)

!
